### PR TITLE
Add start-app package install instructions

### PR DESCRIPTION
**Pull request by dtchepak**
As a newcomer to Elm I tried to get "hello world" working using the provided example but wasn't sure how to download the package.
Added a "Getting Started" section based on the one in elm-html[1](https://github.com/evancz/elm-html/blob/26def0703efda377f669e28d796da71155083935/README.md#get-started) to give readers enough information to type up the example and get it running locally.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
See [my comment](https://github.com/evancz/start-app/issues/23#issuecomment-142818516) over at the related issue.

**Comment by dgendill** [comment]
This pull request seems like a good idea.  As a complete beginner, I initially tried running `elm-package install StartApp` and was confused when the terminal said "StartApp is not a valid package".  So I think it would definitely be helpful to provide some install instructions for those who are not familiar with the package system.

**Comment by jesusgollonet** [comment]
:+1: 
Of course the info can be found elsewhere, but if start-app is supposed to be the entry point it makes sense to have all instructions in this readme

**Comment by rudolf-adamkovic** [comment]
+1 Came here while searching how to install this.

**Pull request closed without merging**
