### PR TITLE
expose inputs on StartApp.App

### PR DESCRIPTION
**Pull request by ujal**
Exposing inputs on app makes it possible to react to elm actions from javascript. Similar to focusing elements in the elm-todomvc example. Makes it in my opinion more beginner friendly.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
That code doesn't type-check.

**Comment by jvoigtlaender** [comment]
It still doesn't type-check. I think it's a good idea to consult the compiler before submitting a pull request. :smile:

**Comment by ujal** [comment]
Couldn't even change three lines of code without the compiler…

**Comment by jvoigtlaender** [comment]
Actually, my latest comment was wrong. After your fix it _should_ type-check. :smile:

**Pull request closed without merging**
